export const  ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';

export const  UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR';



export const  GETBYID_EMPLOYEE_REQUEST = 'GETBYID_EMPLOYEE_REQUEST';
export const GETBYID_EMPLOYEE_SUCCESS = 'GETBYID_EMPLOYEE_SUCCESS';
export const GETBYID_EMPLOYEE_ERROR = 'GETBYID_EMPLOYEE_ERROR';

export const RESET_EMPLOYEE_STATE = 'RESET_EMPLOYEE_STATE';